"""add color monthly_budget rollover to categories

Revision ID: 46f135f246df
Revises: 554be64199b5
Create Date: 2026-05-23 15:30:43.540303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46f135f246df'
down_revision = '554be64199b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('monthly_budget', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rollover', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('rollover')
        batch_op.drop_column('monthly_budget')
        batch_op.drop_column('color')

    # ### end Alembic commands ###
