"""add regret tagging to expenses

Revision ID: 554be64199b5
Revises: b81ac3bd751a
Create Date: 2026-05-20 09:39:35.409048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554be64199b5'
down_revision = 'b81ac3bd751a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_regret', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('regret_note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('regret_note')
        batch_op.drop_column('is_regret')

    # ### end Alembic commands ###
