"""Initial schema

Revision ID: aa3895bf1742
Revises: 
Create Date: 2026-08-03 19:22:10.579385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3895bf1742'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_mail', sa.String(length=255), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('user_phone', sa.String(length=255), nullable=False),
    sa.Column('user_pass', sa.String(length=255), nullable=False),
    sa.Column('totp_secret', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.Unicode(length=20), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('monthly_budget', sa.Float(), nullable=True),
    sa.Column('rollover', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('expenses',
    sa.Column('expense_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expense_amount', sa.Integer(), nullable=False),
    sa.Column('expense_title', sa.String(length=255), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('expense_note', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('is_regret', sa.Boolean(), nullable=True),
    sa.Column('regret_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('expense_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    op.drop_table('categories')
    op.drop_table('User')
    # ### end Alembic commands ###
